# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pzhang/chen/bed

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pzhang/chen/bed

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pzhang/chen/bed/CMakeFiles /home/pzhang/chen/bed/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pzhang/chen/bed/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named GenSphere1

# Build rule for target.
GenSphere1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 GenSphere1
.PHONY : GenSphere1

# fast build rule for target.
GenSphere1/fast:
	$(MAKE) -f CMakeFiles/GenSphere1.dir/build.make CMakeFiles/GenSphere1.dir/build
.PHONY : GenSphere1/fast

#=============================================================================
# Target rules for targets named perbed

# Build rule for target.
perbed: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 perbed
.PHONY : perbed

# fast build rule for target.
perbed/fast:
	$(MAKE) -f CMakeFiles/perbed.dir/build.make CMakeFiles/perbed.dir/build
.PHONY : perbed/fast

#=============================================================================
# Target rules for targets named GenSphere2

# Build rule for target.
GenSphere2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 GenSphere2
.PHONY : GenSphere2

# fast build rule for target.
GenSphere2/fast:
	$(MAKE) -f CMakeFiles/GenSphere2.dir/build.make CMakeFiles/GenSphere2.dir/build
.PHONY : GenSphere2/fast

#=============================================================================
# Target rules for targets named perbed_gpu

# Build rule for target.
perbed_gpu: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 perbed_gpu
.PHONY : perbed_gpu

# fast build rule for target.
perbed_gpu/fast:
	$(MAKE) -f CMakeFiles/perbed_gpu.dir/build.make CMakeFiles/perbed_gpu.dir/build
.PHONY : perbed_gpu/fast

GenSphere1.o: GenSphere1.cpp.o

.PHONY : GenSphere1.o

# target to build an object file
GenSphere1.cpp.o:
	$(MAKE) -f CMakeFiles/GenSphere1.dir/build.make CMakeFiles/GenSphere1.dir/GenSphere1.cpp.o
.PHONY : GenSphere1.cpp.o

GenSphere1.i: GenSphere1.cpp.i

.PHONY : GenSphere1.i

# target to preprocess a source file
GenSphere1.cpp.i:
	$(MAKE) -f CMakeFiles/GenSphere1.dir/build.make CMakeFiles/GenSphere1.dir/GenSphere1.cpp.i
.PHONY : GenSphere1.cpp.i

GenSphere1.s: GenSphere1.cpp.s

.PHONY : GenSphere1.s

# target to generate assembly for a file
GenSphere1.cpp.s:
	$(MAKE) -f CMakeFiles/GenSphere1.dir/build.make CMakeFiles/GenSphere1.dir/GenSphere1.cpp.s
.PHONY : GenSphere1.cpp.s

GenSphere2.o: GenSphere2.cpp.o

.PHONY : GenSphere2.o

# target to build an object file
GenSphere2.cpp.o:
	$(MAKE) -f CMakeFiles/GenSphere2.dir/build.make CMakeFiles/GenSphere2.dir/GenSphere2.cpp.o
.PHONY : GenSphere2.cpp.o

GenSphere2.i: GenSphere2.cpp.i

.PHONY : GenSphere2.i

# target to preprocess a source file
GenSphere2.cpp.i:
	$(MAKE) -f CMakeFiles/GenSphere2.dir/build.make CMakeFiles/GenSphere2.dir/GenSphere2.cpp.i
.PHONY : GenSphere2.cpp.i

GenSphere2.s: GenSphere2.cpp.s

.PHONY : GenSphere2.s

# target to generate assembly for a file
GenSphere2.cpp.s:
	$(MAKE) -f CMakeFiles/GenSphere2.dir/build.make CMakeFiles/GenSphere2.dir/GenSphere2.cpp.s
.PHONY : GenSphere2.cpp.s

perbed.o: perbed.cpp.o

.PHONY : perbed.o

# target to build an object file
perbed.cpp.o:
	$(MAKE) -f CMakeFiles/perbed.dir/build.make CMakeFiles/perbed.dir/perbed.cpp.o
.PHONY : perbed.cpp.o

perbed.i: perbed.cpp.i

.PHONY : perbed.i

# target to preprocess a source file
perbed.cpp.i:
	$(MAKE) -f CMakeFiles/perbed.dir/build.make CMakeFiles/perbed.dir/perbed.cpp.i
.PHONY : perbed.cpp.i

perbed.s: perbed.cpp.s

.PHONY : perbed.s

# target to generate assembly for a file
perbed.cpp.s:
	$(MAKE) -f CMakeFiles/perbed.dir/build.make CMakeFiles/perbed.dir/perbed.cpp.s
.PHONY : perbed.cpp.s

perbed_gpu.o: perbed_gpu.cpp.o

.PHONY : perbed_gpu.o

# target to build an object file
perbed_gpu.cpp.o:
	$(MAKE) -f CMakeFiles/perbed_gpu.dir/build.make CMakeFiles/perbed_gpu.dir/perbed_gpu.cpp.o
.PHONY : perbed_gpu.cpp.o

perbed_gpu.i: perbed_gpu.cpp.i

.PHONY : perbed_gpu.i

# target to preprocess a source file
perbed_gpu.cpp.i:
	$(MAKE) -f CMakeFiles/perbed_gpu.dir/build.make CMakeFiles/perbed_gpu.dir/perbed_gpu.cpp.i
.PHONY : perbed_gpu.cpp.i

perbed_gpu.s: perbed_gpu.cpp.s

.PHONY : perbed_gpu.s

# target to generate assembly for a file
perbed_gpu.cpp.s:
	$(MAKE) -f CMakeFiles/perbed_gpu.dir/build.make CMakeFiles/perbed_gpu.dir/perbed_gpu.cpp.s
.PHONY : perbed_gpu.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... GenSphere1"
	@echo "... perbed"
	@echo "... edit_cache"
	@echo "... GenSphere2"
	@echo "... rebuild_cache"
	@echo "... perbed_gpu"
	@echo "... GenSphere1.o"
	@echo "... GenSphere1.i"
	@echo "... GenSphere1.s"
	@echo "... GenSphere2.o"
	@echo "... GenSphere2.i"
	@echo "... GenSphere2.s"
	@echo "... perbed.o"
	@echo "... perbed.i"
	@echo "... perbed.s"
	@echo "... perbed_gpu.o"
	@echo "... perbed_gpu.i"
	@echo "... perbed_gpu.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

